version: "2"

services:

  ## NGINX
  nginx:
    image: nginx
    ports:
      - "8510:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    links:
      - php

  php:
    image: php:7.1-fpm
    volumes:
      - ./:/usr/share/nginx/html
      - ./logs:/var/log
